# Follow https://tailscale.com/kb/1114/pi-hole/ specifically steps 3 and 4
--- # Specifies the start of the file
version: "3" # The version of docker compose it uses
services: # The services it will provide
  tailscaled:
    privileged: true
    cap_add:
      - NET_ADMIN # Required for tailscale to work
      - NET_RAW # Required for tailscale to work
    command:
      - /usr/local/bin/containerboot
    restart: unless-stopped # The container always restarts unless stopped by user
    container_name: tailscaled # Name of container
    network_mode: "host" # Required for tailscale to work
    environment:
      - TS_AUTHKEY=tskey-auth-kTHQDf5CNTRL-812JUoHTcRNE6CgxKA9mQNcKRZ4vQQ28 # Authenticates with your account https://tailscale.com/kb/1085/auth-keys/
      - TS_ACCEPT_DNS=false # Required for pihole https://tailscale.com/kb/1114/pi-hole/
    hostname: matthew-vps-googlecloudserver # This will become the tailscale device name
    image: tailscale/tailscale:latest # The image the container will use
    ipc: private # Makes the memory allocated not shared
    logging:
      driver: json-file
      options: {}
    # Volumes store your data between container upgrades
    volumes:
      - ./Tailscale/var_lib:/var/lib # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
